import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { SUPABASE_SQL } from '../app/connect.js';
const db=new PGlite();
await db.exec('create role anon; create role authenticated; create table public.orbit_sync(id text); grant all on public.orbit_sync to anon;');
await db.exec(SUPABASE_SQL);
await db.exec('set role anon');
await assert.rejects(db.query('select * from public.orbit_sync_v2'));
await assert.rejects(db.query('select * from public.orbit_sync'));
const room='a'.repeat(32), otherRoom='b'.repeat(32),device='c'.repeat(24),writer='d'.repeat(64);
await db.query('select public.orbit_push_v2($1,$2,$3,$4)',[room,device,writer,'encrypted one']);
await assert.rejects(db.query('select public.orbit_push_v2($1,$2,$3,$4)',[room,device,'e'.repeat(64),'tampered']));
assert.equal((await db.query('select * from public.orbit_pull_v2($1)',[otherRoom])).rows.length,0);
let rows=(await db.query('select * from public.orbit_pull_v2($1)',[room])).rows;
assert.equal(rows[0].payload,'encrypted one');assert.equal(rows[0].writer,undefined);
await db.query('select public.orbit_push_v2($1,$2,$3,$4)',[room,device,writer,'encrypted two']);
rows=(await db.query('select * from public.orbit_pull_v2($1)',[room])).rows;
assert.equal(rows[0].payload,'encrypted two');
await assert.rejects(db.query('select public.orbit_push_v2($1,$2,$3,$4)',['invalid',device,writer,'bad']));
await db.close();
console.log('Sync SQL: table isolation, room isolation, writer ownership and updates passed');
